version: '2'

services:

  nginx:
    build:
      context: docker/nginx
    ports:
      - 80:8083
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - php
    user: user

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www/html
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    user: user

  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=common404"
      - "MYSQL_DATABASE=laravel"
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/mysqlConfig/log/mysql.log:/var/log/mysql/mysql.log
      - ./docker/mysqlConfig/my.cnf:/etc/mysql/my.cnf
    ports:
      - "33065:3306"

networks:
  network-freandly:

